### ISSUE TITLE
handling multiple openapi .yaml files

### ISSUE THREAD

**Issue by cezarneaga** [fabien0102/openapi-codegen#102]
Hi there,

this works great and i really like the DX it provides. I was wondering how would you handle multiple openapi source files? say your api is split in more than one .yaml file?

do i need to create multiple `openapi-codegen.config.ts` files and pass `--config [name-of-config-file]` to the `npx openapi-codegen gen lmwr` command? or is there another way i should go about this. i don't want to overwrite the fetcher and context files.

cheers,
C

**Comment by fabien0102** [comment]
This is already handled 😁 

You can just re-run `openapi-codegen init` to setup as many api as you want, each of them will have a "namespace":

![image](https://user-images.githubusercontent.com/1761469/192768346-e46ab127-a9f1-4465-ad31-b154f366d8f6.png)


You need to use this namespace to gen the correct, so if you enter `myapp` you will do `npx openapi-codegen gen myapp`

In you example `lmwr` is actually one configuration (the key in `openapi-codegen.config.ts`) 😉

**Comment by cezarneaga** [comment]
ok. got it. i thought there must be something. 😄  thanks.

**Comment by cezarneaga** [comment]
is there also a way to configure it to reuse the fetcher and context? besides doing it manually?

**Comment by needim** [comment]
hmm maybe this can help? https://github.com/networknt/openapi-bundler

**Comment by needim** [comment]
hmm, https://redocly.com/docs/cli/commands/bundle/

**Comment by needim** [comment]
So, if I understood correctly you have one main spec and that spec points to different sub specs with ref path, right?

**Comment by cezarneaga** [comment]
our api is very big so it is split by domain into separate files. the baseUrl is the same for all, auth is the same for all. there isn't one main spec with subs. just multiple files sharing the same baseUrl

**Comment by needim** [comment]
for now, looks like you can bundle it by `redocly cli`

> [redocly.com/docs/cli/commands/bundle](https://redocly.com/docs/cli/commands/bundle/)

can you try to bundle it manually and test it with generated bundled spec? Also looks like we should consider adding support for multiple spec files. I did some research and it looks common enough.

**Comment by fabien0102** [comment]
+1 for redocly, we are using the exact same tool in my company to bundle our openapi specs 😁

**Comment by cezarneaga** [comment]
i get `Can't resolve $ref` errors from redocly 🤷🏻‍♂️

**Comment by needim** [comment]
Can you share the trimmed versions of the 2 specs? So I can test.
