### ISSUE TITLE
How to access headers from fetch functions?

### ISSUE THREAD

**Issue by B4rtware** [fabien0102/openapi-codegen#110]
For authentication in my application, I use a single endpoint for retrieving a CSRF token. This returns a new CSRF token inside the header `X-CSRFToken` . I need to extract this header from the response and store it inside memory.
Prior to the `openapi-codegen`, it was possible to it like so:
```typescript
authGetCsrf()
  .then((response) => {
    const csrfToken = response.headers["x-csrftoken"];
    setCsrf(csrfToken);
  })
```
Now I can't do this anymore because the response object is missing. I can access it inside the `fetcher.ts`:
```typescript
  [...]
  if (response.headers.has("x-csrftoken")) {
    console.log(`TOKEN: ${response.headers.get("x-csrftoken")}`)
  }
  [...]
```
But it seems like this doesn't help with the problem because I would then need it to store within my `Auth` context and I can't use hooks inside the `fetcher.ts` only inside the `context.ts`.
Is there anything I can do about it?

Possible workarounds could be:
- Use an extra fetch function besides the generated client
- Use an extra fetch function inside the `context.ts` not the generated one
- Return the CSRF token inside the body

but really only if it isn't possible

**Comment by needim** [comment]
Hi @B4rtware, Tanstack Query only resolves promises or throws errors. So we can't access headers in custom hooks.

If you wanna access headers you need to handle them in fetcher. 

I don't know how your Auth context handles CSRF tokens, but probably it is written in local storage or cookie right?

Maybe you can just write the local storage/cookie directly in fetcher.ts and your auth context will read from there?

**Comment by B4rtware** [comment]
Hi, thanks again for the fast response :)
I am using this as a guide for the implementation: [Django Session-based Auth for Single Page Apps](https://testdriven.io/blog/django-spa-auth). There they just store it inside the memory.
Using the local storage seems to be a good idea. I will use this option.
