### ISSUE TITLE
missing "SIGNAL" after update

### ISSUE THREAD

**Issue by el-j** [fabien0102/openapi-codegen#115]
Hi, i am currently running into a problem with the "signal" after i updated to the newest version. 
how do i migrate? do you have any help for that?

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/2795534/200592494-54214924-dbe6-4e80-90fa-3cac557b2e07.png">

thanks in advance

**Comment by el-j** [comment]
ok fixed it, with "signal?:any" inside of the `FetcherOptions` interface. 

<img width="629" alt="image" src="https://user-images.githubusercontent.com/2795534/200593760-41ee53e8-14fd-466b-a581-7879c83a9f68.png">

but i was using a completely new `open-api codegen init` so this argument should be included from the generator

**Comment by needim** [comment]
hi, it is already there https://github.com/needim/openapi-codegen/blob/main/plugins/typescript/src/templates/fetcher.ts#L47

but I am not sure how you didn't get the parameter on generated fetcher.
