### ISSUE TITLE
Error response type

### ISSUE THREAD

**Issue by jamalsoueidan** [fabien0102/openapi-codegen#150]
Hello,

Thanks for creating this cli codegen, I love it.

I faced a small issue with response model for status code 400:

```
"400":
      $ref: "../../responses/error.yaml"
 ```

which consist of object with 2 keys {success, error}

but when using the openapi-codegen it resolve them like this:

```
export type CreateUserApiError = Fetcher.ErrorWrapper<{
  status: 400;
  payload: Responses.ErrorResponse;
}>;
```

when I call createUserApi, and it throws an error, the error object is:

```
const { mutate, error } = useCreateUserApi();
console.log(error);
{name: 'unknown', message: 'Network error', stack: {…}}
```

I'm missing something?

Shouldn't error contain my ErrorResponse object?

**Comment by jamalsoueidan** [comment]
In vscode the error is: 
const error: CreateUserApiError | null

But this is not right?

**Comment by fabien0102** [comment]
Hey 👋 
The generated type looks correct, the `Fetcher.ErrorWrapper<>` is adding this ` {status: "unknown"}`, you can have a look into the generated `{namespace}Fetcher.ts` file.

You seams to have a Network error somewhere, I can’t really tell more from here. This is the default behaviour:
```ts
// {namespace}Fetcher.ts-71:86
if (!response.ok) {
      let error: ErrorWrapper<TError>;
      try {
        error = await response.json();
      } catch (e) {
        error = {
          status: "unknown" as const,
          payload:
            e instanceof Error
              ? `Unexpected error (${e.message})`
              : "Unexpected error",
        };
      }

      throw error;
      }
```

So for example, if the error doesn’t send back a json, this will fallback. try to add some `console.log` over here 😉

**Comment by jamalsoueidan** [comment]
Maybe you can see what's wrong?

Application: https://victorious-water-04353a503.2.azurestaticapps.net/
Openapi: https://github.com/jamalsoueidan/booking-api/blob/main/openapi/paths/auth/receive-password.yaml

**Comment by fabien0102** [comment]
I can try to have a look on Tuesday 😉

**Comment by jamalsoueidan** [comment]
> I can try to have a look on Tuesday 😉

Happy Easter ;)

**Comment by fabien0102** [comment]
I just had a quick look, but I don’t really see where is the call in your codebase, you can ping me on https://xata.io/discord (@fabien0102#6706) so you can walk me through the codebase, this will be easier ;)

**Comment by jamalsoueidan** [comment]
https://github.com/jamalsoueidan/booking-admin/blob/main/src/App.tsx

it's fresh react app, only this code, first call to login may take few sec to boot up the instance on azure function.

**Comment by jamalsoueidan** [comment]
The login gives wrong phone number, to receive error :) the success is correct and works as expected.

**Comment by vahidvdn** [comment]
I have the same issue here. This library wraps the type inside `{status, payload}`, however I just send the error object without any status, payload.  So this is how I log my error:

```ts
console.log(error?.message, error?.statusCode);
```

But typescript expects status and payload. Which is wrong. Any idea how to fix this?

**Comment by vahidvdn** [comment]
I guess the problem is [here](https://github.com/fabien0102/openapi-codegen/blob/88e09cc6c2216ab50341623c29622051c8220d6e/plugins/typescript/src/core/getErrorResponseType.ts#L184):

```ts
return f.createTypeLiteralNode([
    f.createPropertySignature(undefined, "status", undefined, statusType),
    f.createPropertySignature(undefined, "payload", undefined, type),
]);
```

It should not wrap like this. Any idea?
