### ISSUE TITLE
Support for react query 5

### ISSUE THREAD

**Issue by rajzik** [fabien0102/openapi-codegen#176]
React query is currently working on v5 and API seems to be stable.

https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5 

Would it be possible to add version to the generator?

**Comment by unrealsolver** [comment]
That looks doable to me. It's just a change in the templates.

**Comment by rajzik** [comment]
@unrealsolver Create PR for this issue. @fabien0102 please have a look.
