### ISSUE TITLE
Change window.fetch to fetch

### ISSUE THREAD

**Issue by SeverinBucher** [fabien0102/openapi-codegen#180]
Generated code uses window.fetch to fetch from the backend api. The window object is only available in the browser.
https://github.com/fabien0102/openapi-codegen/blob/23ed5edb9cf3887c25e5edef7a59aeb5b8b48614/plugins/typescript/src/templates/fetcher.ts#L91

I would like to do server side rendering. This means I have to be able to fetch data with nodeJS.

- Currently all browser seams to alias `window.fetch` to `fetch`. 
- nodeJS 18+ supports fetch natively.

I'm willing to work on this issue. It looks like an easy fix.

Motivation:
I'm using openapi-codegen to generate code to use in a frontend framework using nodeJS. Server-side-rendering is a basic feature supported by all well known frameworks. So far the generated code cannot be used directly because on the server there is no window object. After this fix every framework using nodeJS v18+ can use the generated code directly with no impact on the client side code.

**Comment by fabien0102** [comment]
Hey!
This is not an issue since the `{namespace}fetcher` file is only generated once and is meant to be tweaked depending on your need 😉 
You can also use another fetch library or whatever you want as soon as the signature is fulfilled.

**Comment by SeverinBucher** [comment]
Thanks for looking at it. Just a follow up question. Is there a benefit of using `window` in any case?

**Comment by fabien0102** [comment]
No real benefit, it's more about habit, I do prefer explicit things so you know that we are using the global fetch and not an external library. I think I start using `window.fetch` instead of `fetch` after some weird TypeScript issues (probably fixed now).

**Comment by WildEgo** [comment]
> No real benefit, it's more about habit, I do prefer explicit things so you know that we are using the global fetch and not an external library. I think I start using `window.fetch` instead of `fetch` after some weird TypeScript issues (probably fixed now).

To bring this back up but, that does create issues with things that do not have a window such as, nodejs anything with ssr and probably more that I do not know, if not to remove window directly at least make it an opt out
