### ISSUE TITLE
Is it possible to not expose fetch methods?

### ISSUE THREAD

**Issue by Richard87** [fabien0102/openapi-codegen#202]
Hi!

We need React Context in our fetch (to get a valid auth token). 

If fetchXXX is used directly this will not work. Is it possible to not expose those methods?

or even better, automatically add all as a api client hook:
```js
const api = useApi()
api.fetchXYZ()
```

**Comment by fabien0102** [comment]
Hi,
You can use the context and fetcher files for this. Those files are only generated when they don't exists and meant to be tweak for this exact usecase 

You can see an example here -> https://github.com/fabien0102/openapi-codegen/blob/138a808be699cc65383708744e72ffe26b85b9eb/examples/frontend/src/github/githubContext.ts#L47

**Comment by Richard87** [comment]
Hi! 

Thanks for the explanation, that helps a lot 🙏
