### ISSUE TITLE
Handle multiple-valued query parameters in queryParams

### ISSUE THREAD

**Issue by ceefour** [fabien0102/openapi-codegen#214]
Currently `queryParams` assumes that queryParams is a `Record`, meaning it's not possible to have, e.g.

`https://example.com/?branch=valueA&branch=valueB`

Note: `URLSearchParams` already supports multiple valued query parameters (appending parameters with the same name).

This should be fixed to allow multiple values.

**Comment by unrealsolver** [comment]
@ceefour please take a look, https://github.com/fabien0102/openapi-codegen/pull/218
You can copy this to your *Fetcher.ts file

**Comment by fabien0102** [comment]
As mentionned in your pull-request, `{namespace}Fetcher.ts` is a template copied once, so you can tweak it as much as you want to fit your usecase 😉
