### ISSUE TITLE
After running tsc --build, and compiling generated react-query hooks to .js and .d.ts files, I encountered the error message "No QueryClient set, use QueryClientProvider to set one".  It seems that hooks lose the context of the react-query..

### ISSUE THREAD

**Issue by detoner777** [fabien0102/openapi-codegen#246]
I built a private npm package that has generated  tanstack-query hooks with their types and compiles them into .js and .d.ts files. This package facilitates sharing requests and types across web/react-native projects.

Here's how the package.json file looks:
```json
{
  "name": "@core/react-query-operations",
  "version": "2.0.8",
  "description": "Test",
  "license": "UNLICENSED",
  "type": "commonjs",
  "main": "dist/index.d.ts",
  "typings": "dist/index.d.ts",
  "files": [
    "dist",
    "generated",
    "README.md"
  ],
  "scripts": {
    "codegen": "npx openapi-codegen gen mainframe",
    "build": "tsc --build"
  },
  "devDependencies": {
    "@openapi-codegen/cli": "2.0.1",
    "@openapi-codegen/typescript": "8.0.1",
    "@types/react": "18.2.75",
    "typescript": "5.3.3"
  },
  "peerDependencies": {
    "@tanstack/react-query": "^5.29.0"
  }
}
```
Project structure resembles this:
<img width="385" alt="image" src="https://github.com/fabien0102/openapi-codegen/assets/46618408/7cb7a47e-d8ff-448b-a196-c54829b13fc8">

<img width="371" alt="image" src="https://github.com/fabien0102/openapi-codegen/assets/46618408/57aaed77-2034-4397-943c-8cd45ebec486">

I used QueryProvider and all necessary configuration for the React-Query library.
Upon importing this package hooks into my Next app, I encountered the error message mentioned above.

Here's a visual representation of the error:

<img width="807" alt="image" src="https://github.com/fabien0102/openapi-codegen/assets/46618408/072668bd-c503-4010-b872-3dbbc145fba9">

Upon investigation, I confirmed that none of the react-query additional versions were used in my project. It seems that after compilation, the generated hooks lose the QueryProvider context.  Additionally, the error did not occur when importing package directly as .ts files without compilation. But in this case, I need to use **babel-loader** and addition **webpack** config to read .ts files.

**Comment by fabien0102** [comment]
Hey, depending of your openapi-codegen config you can generate tanstack-query hooks. If you are generating them, you need to setup your project accordingly following this tutorial -> https://tanstack.com/query/v4/docs/framework/react/quick-start

In short, you need to have a QueryProvider at the top level of your application 😉 I hope this helps!

**Comment by detoner777** [comment]
> Hey, depending of your openapi-codegen config you can generate tanstack-query hooks. If you are generating them, you need to setup your project accordingly following this tutorial -> https://tanstack.com/query/v4/docs/framework/react/quick-start
> 
> In short, you need to have a QueryProvider at the top level of your application 😉 I hope this helps!

@fabien0102, my apologies if I haven't been specific enough. I did indeed use QueryProvider and configured everything accordingly. As I previously mentioned, the generated queries function properly with the react-query library when imported as .ts functions. However, upon compilation using **tsc --build** to **.js** with **.d.ts**, it seems like the hooks no longer recognize QueryProvider, it's as if they lose this context. I'm hoping to receive some ideas on how to resolve this issue.

**Comment by fabien0102** [comment]
Hello, sorry for the late answer, I have no idea of your setup, but you need to compile jsx and everything properly, for frontend I can suggest using vite instead of tsc.

https://vitejs.dev/guide/

This should take care of all the mess we have in the frontend world and even have a little dev server for free (with hotreload on so on :) )

**Comment by fabien0102** [comment]
I will close this issue for tracking purpose, since this about your environment and not a problem with the generator, but please free to keep chatting here!
