### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'path' imported from

### ISSUE THREAD

**Issue by moltar** [fabien0102/openapi-codegen#33]
Keep getting the following error:

```sh
npx openapi-codegen
```

> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'path' imported from /.../node_modules/@openapi-codegen/cli/lib/commands/GenerateCommand.js

Any ideas?

**Comment by fabien0102** [comment]
mmmm, what version of nodejs do you have? 🤔

**Comment by fabien0102** [comment]
Wait! this is not my package ^^

This is mine:
```bash
 $ npx @openapi-codegen/cli --help
 ```

**Comment by moltar** [comment]
> mmmm, what version of nodejs do you have? 🤔

v14.17.6

**Comment by moltar** [comment]
> Wait! this is not my package ^^

🤔 hm, interesting.

Because before install your package that command did not exist, but when I installed it, then it exists but fails.

Will try npx @openapi-codegen/cli

**Comment by fabien0102** [comment]
Since I didn't have the time yet to do the `init` command, you can install `@openapi-codegen/cli` and `@openapi-codegen/typescript` and follow this readme https://github.com/fabien0102/openapi-codegen/tree/main/cli

**Comment by moltar** [comment]
> https://github.com/fabien0102/openapi-codegen/blob/fad67ded953f4e4d86c8053ffe322f2778f94d1a/cli/package.json#L9

This would definitely install `openapi-codegen` into `node_modules/.bin/`

**Comment by fabien0102** [comment]
> > https://github.com/fabien0102/openapi-codegen/blob/fad67ded953f4e4d86c8053ffe322f2778f94d1a/cli/package.json#L8-L10
> 
> This would definitely install `openapi-codegen` into `node_modules/.bin/`

Indeed, but `openapi-codegen` package also, and the bin name is not the same as the package name 😕

**Comment by moltar** [comment]
> Since I didn't have the time yet to do the `init` command, you can install `@openapi-codegen/cli` and `@openapi-codegen/typescript` and follow this readme https://github.com/fabien0102/openapi-codegen/tree/main/cli

Ok, that's what I did. And the original issue is the result of that :)

**Comment by fabien0102** [comment]
Ah, you did `npx` in a folder where the package was installed! I didn't test the same, my bad

**Comment by fabien0102** [comment]
I have node `16.13.1` locally, let me try with the 14

**Comment by moltar** [comment]
> Ah, you did `npx` in a folder where the package was installed! I didn't test the same, my bad

What do you mean by that?

What's the proper solution?

I think maybe a quick demo repo with the example of the correct setup would be great in this case 😁 🙏🏼

**Comment by fabien0102** [comment]
> > Ah, you did `npx` in a folder where the package was installed! I didn't test the same, my bad
> 
> What do you mean by that?
> 
> What's the proper solution?
> 
> I think maybe a quick demo repo with the example of the correct setup would be great in this case 😁 🙏🏼

I'm totally with you, and this is in my todolist since a long time 😅 but time… time… 

I meant I was trying `npx` in a random folder for reproducing, so this was using `openapi-codegen` instead of my package ^^, but if you install a package and after run `npx` this is actually working 😉 sorry for the mess ^^

**Comment by moltar** [comment]
But `openapi-codegen` _is_ your package 😁

... so I don't understand?

**Comment by fabien0102** [comment]
> But `openapi-codegen` _is_ your package 😁
> 
> ... so I don't understand?

https://www.npmjs.com/package/openapi-codegen <- this one is not! ^^

**Comment by moltar** [comment]
1. I installed `@openapi-codegen/cli`, `@openapi-codegen/typescript`
2. I'm in the project root
3. I run `npx openapi-codegen` (which just runs `node_modules/.bin/openapi-codegen` (which is your package)

**Comment by moltar** [comment]
```
❯ head -n5 node_modules/.bin/openapi-codegen
#!/usr/bin/env node
import { Cli } from "clipanion";
import { GenerateCommand } from "./commands/GenerateCommand.js";
import { InitCommand } from "./commands/InitCommand.js";
import { readFileSync } from "fs";
```

Isn't that your package?

**Comment by moltar** [comment]
> > https://github.com/fabien0102/openapi-codegen/blob/fad67ded953f4e4d86c8053ffe322f2778f94d1a/cli/package.json#L8-L10
> 
> This would definitely install `openapi-codegen` into `node_modules/.bin/`

As I pointed out here. Your package specifies to install `openapi-codegen` binary ...

**Comment by moltar** [comment]
Which gets installed into `node_modules/.bin/openapi-codegen`

**Comment by fabien0102** [comment]
You are actually in the correct package, I was not when I tried to repro with `npx`, give me 10mn to try with node 14, since I was force to use the latest module feature for fetch, this is maybe why ;)

**Comment by moltar** [comment]
Which then gets run thru `npx openapi-codegen`

**Comment by moltar** [comment]
You are right, it works with 16!

**Comment by moltar** [comment]
But I cannot upgrade to 16 yet 😢

**Comment by fabien0102** [comment]
![image](https://user-images.githubusercontent.com/1761469/155132345-feb647b4-156a-48f1-93e8-b46b51f9bdb4.png)

And you are right, this is not working with 14 😖

**Comment by moltar** [comment]
It works like this:

```diff
- import path from "path/posix";
+ import path from "path";
```

**Comment by fabien0102** [comment]
![image](https://user-images.githubusercontent.com/1761469/155133136-b21389da-e12c-4729-8b82-30b5011467d6.png)

Sorry, you will be blocked just after! maybe with some nodejs flags somewhere… let me check

**Comment by moltar** [comment]
Oh, I see what you are doing. You are crafting the path, and then using dynamic imports to load the config.

**Comment by fabien0102** [comment]
Yeah, this is to have a typescript config (so typesafe with autocompletion), but everything have a price, this was hard 😅 but the problem is the `.mjs` due to the dependency `got` (to retrieve distant specs)

**Comment by fabien0102** [comment]
You are rigeht, the problem is `path` indeed, I didn't pay attention to the backslash in my path…

**Comment by moltar** [comment]
ok, this should work cross platform?

```
import path from "path";

path.posix(...)
```

I think the reason why 

```
import path from "path/posix";
```

does not work, is because in older node version there was no `path/posix` file. Maybe it was just exporting posix object from the root file.

**Comment by moltar** [comment]
> Yeah, this is to have a typescript config (so typesafe with autocompletion), but everything have a price, this was hard 😅 but the problem is the `.mjs` due to the dependency `got` (to retrieve distant specs)

![screenshot-20220222T194208-uNg02P49](https://user-images.githubusercontent.com/491247/155134526-4bf80c23-1469-4081-ad5f-10a410640d13.png)

Works with TS too

**Comment by fabien0102** [comment]
I do have a working version! using `slash()` everywhere (my lifesaver package for this kind of problem ^^) I will open a PR

**Comment by moltar** [comment]
I think using posix is fine, and I think slash might not be needed. Just need to use posix like this:

```ts
import path from "path";

path.posix(...)
```

**Comment by fabien0102** [comment]
Let's try!

**Comment by moltar** [comment]
Thanks for fixing so quickly!!

**Comment by moltar** [comment]
It works!! 🎉 

Thanks!

**Comment by moltar** [comment]
> I really need to find more time to write more docs & examples.

Open some issues with what you have in mind and tag me, maybe I can help!

**Comment by moltar** [comment]
Btw, just a tip, you can also write it like this:

https://github.com/fabien0102/openapi-codegen/blob/2105e99f03fe71251cf347e905c88cae9b4a39a1/cli/src/commands/GenerateCommand.ts#L4-L14

```ts
import { posix as path } from 'path'
```

**Comment by fabien0102** [comment]
> Btw, just a tip, you can also write it like this:
> 
> https://github.com/fabien0102/openapi-codegen/blob/2105e99f03fe71251cf347e905c88cae9b4a39a1/cli/src/commands/GenerateCommand.ts#L4-L14
> 
> ```ts
> import { posix as path } from 'path'
> ```

Indeed! will include this in my next PR, thanks for the feedback!
