### ISSUE TITLE
generateSchemaTypes: Take OpenAPI spec "servers" into account?

### ISSUE THREAD

**Issue by olof-nord** [fabien0102/openapi-codegen#43]
Quick question.

If during the code generation, one might want to specify a "baseURL" for the generated components, is it possble?

Taking the petStore as an example:

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Pets"
```

Using this, then the goal would be to get the hook to use `http://petstore.swagger.io/v1/pets` instead of just `/pets` for its call.

One idea is to basically take `context.openAPIDocument.servers[0].url` and uses it as a prefix/base URL for all requests.

**Comment by olof-nord** [comment]
So, looking into this: the ..Components and ..Schemas is generated, but the ..Context and ..Fetcher is only set up as a template, and can/should be edited as per what is needeed?

**Comment by fabien0102** [comment]
Hi @olof-nord 

Yeah `...Context` and `...Fetcher` are just template (https://github.com/fabien0102/openapi-codegen/tree/main/plugins/typescript#generatereactquerycomponents) this is where you should inject the base url.

This was design like this because you may want to switch servers regarding your env (local vs staging vs prod) or not! This is totally up to your needs 😉

**Comment by fabien0102** [comment]
But talking about it, I actually like the idea to use `servers.url.0` as `baseURL` in the initial template if the value exists 💡

**Comment by olof-nord** [comment]
I am getting there! Many thanks for your guidance and feedback @fabien0102.
Closing as the question is answered.
