### ISSUE TITLE
Improve type safety on error responses

### ISSUE THREAD

**Issue by SferaDev** [fabien0102/openapi-codegen#61]
Right now,  ``fetchers`` do not have a way to include error responses types. Add them and make the default fetcher to type the union of them.

Also, create types for inlined responses.

**Comment by fabien0102** [comment]
Some points after a call with @SferaDev to have more context:

The idea is to add a `TError` that can extends all possible errors types in the `fetcher`
![image](https://user-images.githubusercontent.com/1761469/166658469-0e02670f-0bcb-4e1f-a6d6-8f18ad74a53b.png)

Then, since the type will be passed in every operations, this will force the user to implement every error cases (and typescript will warn on every new error introduce in openapi)

**Comment by fabien0102** [comment]
Thinking a bit more about this, some ideas that I would love to integrate to improve the error type safety.

## 1. Adding an `ErrorWrapper` in the `fetcher.ts`

```ts
export NamespaceErrorWrapper<TError> = TError
```

This will permit to easily extend and tweak the error type, as example

```ts
// Adding a fallback error type
export NamespaceErrorWrapper<TError> = TError | { type: "unknown"; message: string; }
```

## 2. Generate a more accurate error type on `components.ts`

```ts
export MyRouteError = NamespaceErrorWrapper<
 | { status: "404"; payload: Responses.NotFoundError } // $ref in openapi
 | { status: "422"; payload: { message: string; field: string; } } // inline in openapi
 | { status: `5${string}`; payload: Responses.BasicError }
>
```

and injecting this error to the fetcher (as describe previously) as generic.

So it's easier to discriminate on `status` to deal with the error.

## 3. Exporting an `AllErrors` union in `components.ts`

```ts
export type AllErrors = Responses.NotFoundError | Responses.BasicError | { message: string; field: string; }
```

So we could use this in as `extends` value in the `fetcher.ts`

```ts
export async function namespaceFetch<
  TData,
  TError extends NamespaceErrorWrapper<{ status: string; payload: AllErrors }>
  /* ... */
>(){}
```

**Comment by SferaDev** [comment]
@fabien0102 I like your proposals.

Just make status a number please (as in ``Response.status``).

And do we really need things like `5${string}`?

**Comment by fabien0102** [comment]
The thing is… in openapi, you can define `5xx` (https://spec.openapis.org/oas/v3.0.3#patterned-fields-0)
![image](https://user-images.githubusercontent.com/1761469/166941537-79a40591-f0b4-4480-99e0-3474d45dfb5a.png)

And also `default`, and this is not making our life easy in term of generation 😓 
I still need to play a bit with TS to see how I can type this properly, so far I'm really happy with the result…

**Comment by SferaDev** [comment]
> The thing is… in openapi, you can define `5xx` (https://spec.openapis.org/oas/v3.0.3#patterned-fields-0)

Then yes it might make sense to use strings.

Although maybe we could have a union without doing any parsing.

```ts
type Status = 200 | 201 | 400 | 404 | "5xx" | "default";
```

And the fetcher will have to discriminate or build the logic they want per union member.

**Comment by fabien0102** [comment]
I have the pattern to generate the correct error type 😁

![0ae6efe7-d641-4704-88f5-4775769888db](https://user-images.githubusercontent.com/1761469/166968186-b418d5f0-e95a-4d6a-a2c2-0990cdd9ac0f.gif)

So we can have numbers and discriminate properly 🎉
