### ISSUE TITLE
Error to generate code

### ISSUE THREAD

**Issue by carlosrziegler** [fabien0102/openapi-codegen#62]
Getting this error if trying to generate code.

Steps to reproduce this error:
1- create react app ( Vite or CRA)
2- install package: `npm i -D @openapi-codegen/{cli,typescript}`
3- generate code:  `npx openapi-codegen init`

I am missing something?

Thanks

![image](https://user-images.githubusercontent.com/86771140/166638214-7edcdfb1-80cf-4535-87a9-b838d55e8c1c.png)

**Comment by fabien0102** [comment]
🤔 You are missing nothing, this was supposed to work ^^

Maybe a mismatch version with react or something like this 😕 Very strange, I will investigate this, thanks for the repro steps

In the midtime you can create an `openapi-codegen.config.ts` (example [here](https://github.com/fabien0102/openapi-codegen/tree/main/plugins/typescript#generatereactquerycomponents)), the file is typesafe, so it should be good enough for now

**Comment by fabien0102** [comment]
Apparently gatsby ran into the same issue, so we can try to copy the solution 😇 

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/rollup.config.js (see the file history)
