### ISSUE TITLE
No hooks/queries generated in xComponents.ts

### ISSUE THREAD

**Issue by xgp** [fabien0102/openapi-codegen#70]
Hi,

I went through the github example [here](https://xata.io/blog/openapi-typesafe-react-query-hooks) and then tried it on my own openapi spec file [here](https://github.com/p2-inc/phasetwo-docs/blob/master/openapi.yaml). However, there was nothing generated in the xComponents.ts file for using the methods/paths in the openapi spec, only:
```
import * as reactQuery from 'react-query';
import { usePhasetwoContext, PhasetwoContext } from './phasetwoContext';
import type * as Fetcher from './phasetwoFetcher';
import { phasetwoFetch } from './phasetwoFetcher';

export type QueryOperation = {
  path: string;
  operationId: never;
  variables: unknown;
};
```

I used the library like this:
```
$ npm i react-query
$ npm i -D @openapi-codegen/{cli,typescript}
$ npx openapi-codegen init
? Select the source of your OpenAPI Url
? Url https://raw.githubusercontent.com/p2-inc/phasetwo-docs/master/openapi.yaml
? What namespace do you want for your API? phasetwo
? What do you want to generate? React Query components
? Which folder do you want to generate? src/phasetwo
$ npx openapi-codegen gen phasetwo
```

Am I doing something wrong? Is there something unexpected about my openapi spec? It works with all my other tools.

Thanks for the help!

**Comment by fabien0102** [comment]
Hello,
This is because your specs don't have any `operationId` defined (and this is how we can generate the name for your component)

![image](https://user-images.githubusercontent.com/1761469/170078315-e6f5a91e-857a-4f66-8d58-d0d8679bb2c6.png)

**Comment by xgp** [comment]
@fabien0102 Thanks for the fast response! I'll add `operationId` and try again.

**Comment by fabien0102** [comment]
And I will try to add a warning message if the specs doesn't have any `operationId` 😁 Thanks for the feedback, this is always welcome!

**Comment by xgp** [comment]
@fabien0102 adding `operationId` solved my problem. Great tool -- Thank you!
