### ISSUE TITLE
Where to Pass Request Headers?

### ISSUE THREAD

**Issue by el-j** [fabien0102/openapi-codegen#73]
Hi nice project so far. 

i was using  restful-react and was able to add my jwt after sign in to the request header. 
now i am a bit stuck as the new "getters" do not have an option for the header... 

could you please help how to handle that with  openapi-codegen?
![image](https://user-images.githubusercontent.com/2795534/171441716-ef428733-30a6-457c-9d77-4c99b998a3a1.png)

![image](https://user-images.githubusercontent.com/2795534/171441769-5ee48293-e7c1-44d9-9557-a584ff25103f.png)

**Comment by el-j** [comment]
... no sadly not. i am still in need to set the right headers for the request, but i do not know where or how to do it. 
at the moment i have no api connection because of a cors block. 

could you advice please?

**Comment by fabien0102** [comment]
Hi 👋 

You can find a walk through here -> https://xata.io/blog/openapi-typesafe-react-query-hooks

The idea is to inject the headers in the generated `{namespace}Context`

As example this is how we are doing it at xata

1. Add the type
![image](https://user-images.githubusercontent.com/1761469/171579844-d401b6b4-aeeb-418b-b7c9-711fd6c66048.png)

2. Inject the header
![image](https://user-images.githubusercontent.com/1761469/171580005-97984041-73ed-4c29-a5ff-3f81abd9e9de.png)

Here we are in a nextjs context, so we retrieve the header with `useSession`. Everything returns as `fetcherOptions` in the context file are already injected in the fetcher file.

**Comment by fabien0102** [comment]
Adding the types in the step 1 will also add the possibility to pass headers on every request:

![image](https://user-images.githubusercontent.com/1761469/171581788-fe4a65e4-f625-49c5-83c0-4d738841351f.png)

(example with a mutation)

**Comment by el-j** [comment]
hi, thank you very much, that saved my day! 
got the login against the api working again. 

i am building a react frontend and i am soooo happy to work with your piece of art! it helps so much! 🚀 
we can close this here. very good.

one nice thing for the config: override the apiBaseUrl from the swagger, when generating newly, by the value from the config. or do i miss something from the options to do that?
![image](https://user-images.githubusercontent.com/2795534/171592005-eb0b257a-3a54-4332-a557-fae7f3116a21.png)

background: the swagger is from the running build of a project, the dev-api is for my dev-purposes. so if i generate, i always will end up with the wrong api-url in my generated `fetchers.ts`. as it is generated, i do not want to manipulate it by hand or script. could an optional apiBaseUrl override practical for the generator?

i would love it or don't see the option if there is one already ;)

**Comment by el-j** [comment]
or even better:
how to set the apiBaseUrl on runtime, this would be very very nice.

**Comment by fabien0102** [comment]
For the `baseUrl` you can directly modify the `{namespace}Fetcher`, this file is just a template meant to be tweak (and take the url from the spec as example)

If you want to set this value at runtime, you can add this in `FetcherOptions` as for the headers (and inject the value manually on each request or inside the context)

Please note that `{namespace}Fetcher` and `{namespace}Context` are generated only if the files are not there (they don't have the `Generated by @openapi-codegen` header) this is where you can handle any extra logic. This is a different approch from restful-react, where everything was in the config! The nice thing about this, is that you are manipulating real typescript code instead of strings in a config file.

The only constraint that you have are the types, if typescript is happy, you are good to go!

**Comment by el-j** [comment]
Ok in the meantime i changed my config-reader + creator to find the baseUrl in the fetcher.ts file and replace it with a setBaseUrl function that sets the baseUrl as a let for runtime. 
```javascript
fs.readFile(theFetcherFile, 'utf8',(err,data) => {
          if (err) {
            return console.log(err);
          }
          console.log("and its content:>>>>>", data, theFetcherFile);
          let replaceRegEx = /(^const baseUrl = ")+(http[s]?:\/\/)?([^\/\s]+\/)(.*)/gm
          let oldUrl = data.match(replaceRegEx)[0].split('"')[1]
          console.log("old Url",data.match(replaceRegEx),oldUrl)
          let createNewUrl = `let baseUrl:string = ''; export const setBaseUrl = (newUrl: string ,oldUrl: string = "${oldUrl}")=> {  if (!newUrl) {baseUrl=oldUrl; return oldUrl} else {baseUrl=newUrl; return newUrl }};`
          var result = data.replace(replaceRegEx, createNewUrl);
          console.log("and replaceing:::>>>>>>", result);
          return fs.writeFileSync(theFetcherFile, result)
        
        })
```
resulting in a fetcherFile with:
```javascript
let baseUrl: string = '';
export const setBaseUrl = (newUrl: string, oldUrl: string = "https://api.enginsight.com/") => {
  if (!newUrl) { baseUrl = oldUrl; return oldUrl }
  else { baseUrl = newUrl; return newUrl }
};
```

now i set the baseUrl on app-start from the config like i used to do it with restful-react ;)

**Comment by el-j** [comment]
> https://xata.io/blog/openapi-typesafe-react-query-hooks

maybe you could have this link shared in the readme? it helps a lot to understand how to use this nice piece of software ;)
