### ISSUE TITLE
[Bug] - Fetcher tries to get data from frontend url instead of backend one.

### ISSUE THREAD

**Issue by jimmysafe** [fabien0102/openapi-codegen#75]
Hi all! Thanks for making this package available, it looks amazing.

I'm just running into an issue that prevents me from using it..

I have followed up the configuration in the docs but i get the following issue:

here is my configuration file:

```
import {
  generateSchemaTypes,
  generateReactQueryComponents,
} from "@openapi-codegen/typescript";
import { defineConfig } from "@openapi-codegen/cli";

export default defineConfig({
  reviews: {
    from: {
      source: "url",
      url: "https://api.apis.guru/v2/specs/github.com/1.1.4/openapi.yaml",
    },
    outputDir: "generated",
    to: async (context) => {
      const filenamePrefix = "reviews";
      const { schemasFiles } = await generateSchemaTypes(context, {
        filenamePrefix,
      });
      await generateReactQueryComponents(context, {
        filenamePrefix,
        schemasFiles,
      });
    },
  },
});

```

Here we can see that types and everything get generated fine.

<img width="342" alt="Screenshot 2022-07-26 at 13 21 45" src="https://user-images.githubusercontent.com/12184812/180994380-315557ee-4dcd-4976-810c-c8634e45a906.png">

this is my query on React frontend:

<img width="545" alt="Screenshot 2022-07-26 at 13 22 33" src="https://user-images.githubusercontent.com/12184812/180994485-c99f6e55-b4f5-4398-aade-6352c70046b3.png">

and this is the error i encounter on frontend. 

<img width="1702" alt="Screenshot 2022-07-26 at 13 23 15" src="https://user-images.githubusercontent.com/12184812/180994587-0e3f5e94-a689-40bf-8b7a-a71b10c16ddf.png">

i dont know why it is trying to fetch from localhost:3000 (which is where im running my React app on).

I really hope someone can support me on this, would really appreciate :)

**Comment by fabien0102** [comment]
Hi 👋 
Strange, this should works out of the box 🤔 
For instance `reviewsFetcher.ts` is a template (generated only once and tweakable to fit your needs), but when I'm using your configuration, the `baseUrl` is already convigured properly

![image](https://user-images.githubusercontent.com/1761469/181008602-746ee136-3a06-4db9-8a9b-d3c686c28d6d.png)

If you can share a repo with the repro, this may be the easiest. Otherwise some `console.log` into the `reviewsFetcher.ts` to see if the url is resolved properly and try to see what's missing should do it.

**Comment by jimmysafe** [comment]
@fabien0102  thanks very much, my bad i havent read the docs properly. Yes! I had to setup the base url in the fetcher file.
This is how my file looked like:

<img width="411" alt="Screenshot 2022-07-26 at 16 28 12" src="https://user-images.githubusercontent.com/12184812/181032357-8374082b-51f6-4fa2-b035-2b7a7c327020.png">

adding my backend endpoint there (http://localhost:4000) worked perfectly.

Amazing package!

Thanks very much for the quick response @fabien0102.

Keep Up the great work <3

**Comment by fabien0102** [comment]
@jimmysafe No problems, always happy to help 😃 

Note: You are probably not on the last version, the `baseUrl` is inferred from the specs in the latest one (like in my screenshot)
