### ISSUE TITLE
Any plans for adding multipart/form-data support?

### ISSUE THREAD

**Issue by needim** [fabien0102/openapi-codegen#81]
Right now I am trying the codegen on our big codebase (124 controllers and countless methods) and it works perfectly.

I think basic idea is to check if  `requestBody.content` has  `'multipart/form-data'` key and generate mutations accordingly.
And possible `{prefix}fetcher.ts` changes are needed.

I will investigate more but just wanted to ask beforehand.

**Comment by needim** [comment]
With some changes, the generator was able to generate correct definitions. Also, some changes are needed in `{prefix}Fetcher.ts` file to upload operations work, but that is out of scope I guess. (using FormData etc.)

1st change: findCompatibleMediaType.ts
```diff
export const findCompatibleMediaType = (
  requestBodyOrResponseObject: RequestBodyObject | ResponseObject
): MediaTypeObject | undefined => {
  if (!requestBodyOrResponseObject.content) return;
  for (let contentType of Object.keys(requestBodyOrResponseObject.content)) {
    if (
      contentType.startsWith("*/*") ||
      contentType.startsWith("application/json") ||
>      contentType.startsWith("application/octet-stream") ||
>      contentType.startsWith("multipart/form-data")
    ) {
      return requestBodyOrResponseObject.content[contentType];
    }
  }
};
```

2nd change: schemaToTypeAliasDeclaration.ts
```diff
  switch (schema.type) {
    case "null":
      return f.createLiteralTypeNode(f.createNull());
    case "integer":
    case "number":
      return withNullable(
        f.createKeywordTypeNode(ts.SyntaxKind.NumberKeyword),
        schema.nullable
      );
    case "string":
>      if (schema.format === "binary") {
>        return f.createTypeReferenceNode("File");
>      }
      return withNullable(
        f.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
        schema.nullable
      );
```

Generated RequestBody types:
```typescript
export type ArticleImageUploadMutationRequestBody = {
  /*
   * @format binary
   */
  file?: File;
};

export type TaskAttachmentUploadMutationRequestBody = {
  files?: File[];
};
```

**Comment by fabien0102** [comment]
This looks amazing! I don't know why, I always forget about files upload 😅

Can you open a PR? I will be totally happy to add this ti the generator 😊
