### ISSUE TITLE
Idea: passing custom fetcher options from generated hooks

### ISSUE THREAD

**Issue by needim** [fabien0102/openapi-codegen#85]
Hi,

Right now fetcher only can access `fetcherOptions` from the global context.

```typescript
  fetcherOptions: {
    // don't show errors if the request fails
    silent?: boolean;

    // don't send authorization header
    public?: boolean;
  };
```

I was thinking of adding support for passing it from generated hooks.

The basic idea is to add an optional parameter to generated hooks.

```typescript
variables: ....,
options?: ....,
> fetcherOptionsOverride?: {prefix}Context['fetcherOptions']
``` 

And spread the passed parameters into:

```typescript
() => fetchUserQuery({ ...fetcherOptions, ...fetcherOptionsOverride, ...variables }),
```

Possible use cases:

- Normally users will handle errors in their `{prefix}Fetcher.ts`
  - But in some cases, for some operations, users can want to handle errors silently for example.
  - So they can add a `silent?: boolean` param to fetcherOptions and pass that option to custom generated hook

```typescript
const apiKeyQuery = useUserGetApiKeyQuery(
  { pathParams: { id: user.id } }, // <--- variables
  { enabled: Boolean(user.id), onSuccess: setApiKey }, // <--- options
  { silent: true } // <--- optional fetcherOptionsOverride (type-safe)
);
```
- Passing custom headers to handle better window.fetch
  - Some endpoints can be public so no authorization header is needed

It is totally optional feature, but it will add more functionality and support more generic use cases I think.

What do you think?

**Comment by needim** [comment]
Ohhh, wait it is already supported! Never mind closing this.

**Comment by fabien0102** [comment]
My favorite kind of issues 😁 I'm glad it's already implemented ^^
