### ISSUE TITLE
How to set a header value that might change

### ISSUE THREAD

**Issue by xgp** [fabien0102/openapi-codegen#87]
Hi all,

I'm having a problem similar to https://github.com/fabien0102/openapi-codegen/issues/74 where I am setting the authorization header like this:
```
const { data: activeOrg, refetch } = useGetOrganizationById({
    pathParams: { realm: 'self', orgId },
    headers: {
      Authorization: `Bearer ${access_token}`,
    },
  });
```
My problem is that the `access_token` may expire while the page is loaded and component rendered, which will cause an auth error from the server. Is there a better way to do this such that I can specify the header value at request time, so that I can always provide a valid token?

Thanks for any help!

**Comment by needim** [comment]
Hi, I am using generated fetcher for that kind of situations.

**Comment by needim** [comment]
Generated {prefix}Fetcher.ts only created once on init.

It will not regenerate every time. So you can edit it freely. For example you can replace window.fetch with axios also if you want.

In my case if token is not valid, backend throws unathorized error. And I am catching it and request new token with refreshToken and set it again.

**Comment by fabien0102** [comment]
I'm also not in front of my laptop for elaborated example, but you can have a look over here -> https://github.com/fabien0102/openapi-codegen/blob/main/examples/frontend/src/github/githubContext.ts#L47

You can actually tweak the `Fetcher` or/and the `Context` for this kind of usecase (those files are generated once and used by the generated hooks)

**Comment by fabien0102** [comment]
The rule is simple, if you have `Generated by @openapi-codegen` as file header, it's a no-no, if not, you can tweak it 😁

**Comment by xgp** [comment]
Thank you @needim @fabien0102 !

**Comment by needim** [comment]
For the future people: 

The beauty of this generator is flexibility. It gives you base context and fetcher and you can tweak it for your needs. It always generates schemas and hooks but it generates context and fetcher ONLY ONCE. So you can tweak them for your needs and next generate actions are doesn't gonna affect your context or fetcher.

@fabien0102 maybe we should mention this on documentation to make this clear.

**Comment by fabien0102** [comment]
@needim Indeed we need to improve the documentation, if you want to take the lead on this, I will be happy to review (I'm currently moving apartment so not too much free time 😓)

And thanks again for all your contributions! (I'm actually adding you right away in the all contribution list, sorry for latency ^^)

**Comment by cheryl-c-tirerack** [comment]
> It will not regenerate every time. So you can edit it freely. For example you can replace window.fetch with axios also if you want.

I'm sorry - I'm trying this but it is a little more complex than changing window.fetch to axios as the call signatures are very different.
I have a number of endpoints and if I have to manually edit all fetchers, it seems little better than writing my own hooks. What am I missing?

**Comment by fabien0102** [comment]
All your endpoints will call the custom fetcher, this is a simple function that take all you need to do your fetching logic.
As a start, this is using `window.fetch` as you can see in this example (https://github.com/fabien0102/openapi-codegen/blob/35a28b5047ee4ee7e4c0975dec0060d831585a58/examples/frontend/src/github/githubFetcher.ts#L38-L79)

But you can use axios or anything else inside. the `githubFetch` (in our example) will be called by the generated code. This is just a simple wrapper/abstraction.

So we have `useMyEndpoint` that will call `{namespace}Fetch` that will call axios (or something else).
