### ISSUE TITLE
Return type is unknown unless explicitly defined

### ISSUE THREAD

**Issue by Kordonme** [fabien0102/openapi-codegen#88]
We're facing some issues with hooks having an `unknown` return type unless explicitly typed:

```js
const {data: locations} = useListLocations({});
// -> const locations: unknown

const {data: locations} = useListLocations<ListLocationsResponse>({});
// -> const locations: Location[] | undefined
```

```js
// hardcoding the known type fixes the issue:
// export const useListLocations = <TData = ListLocationsResponse>(

export const useListLocations = <TData>(
  variables: ListLocationsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      ListLocationsResponse,
      ListLocationsError,
      TData
    >,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } =
    useOctopusContext(options);
  return reactQuery.useQuery<ListLocationsResponse, ListLocationsError, TData>(
    queryKeyFn({ path: "/locations", operationId: "listLocations", variables }),
    () => fetchListLocations({ ...fetcherOptions, ...variables }),
    {
      ...options,
      ...queryOptions,
    }
  );
};
```

```js
export type Location = {
  /*
   * @format uuid
   */
  id: string;
};
```

I'm not sure how `createTypeParameterDeclaration` works, but might have to do with this line.

https://github.com/fabien0102/openapi-codegen/blob/main/plugins/typescript/src/generators/generateReactQueryComponents.ts#L465

I was under the assumption that the type could be inferred instead of having to type it explicitly. We're using latest version.

**Comment by fabien0102** [comment]
Hey!

I will need a bit more context to be able to help you, what's the generated type of `ListLocationsResponse` ?

**Comment by Kordonme** [comment]
Thanks for the quick answer!

```js
export type ListLocationsResponse = Schemas.Location[];
```

**Comment by Kordonme** [comment]
Oops, my bad. I didn't use `Location[]`, but `ListLocationsResponse`. I've updated with the correct types in the question.

**Comment by fabien0102** [comment]
Strange strange, maybe a regression from https://github.com/fabien0102/openapi-codegen/pull/83 🤔 

Just to be sure, can you give me your react-query & openapi-codegen version?

I'm testing locally to check 😉

**Comment by Kordonme** [comment]
```
"@tanstack/react-query": "^4.2.3",
"@openapi-codegen/cli": "^1.5.2",
"@openapi-codegen/typescript": "^5.1.0",
```

Thanks. Let me know if you need anything.

**Comment by fabien0102** [comment]
![image](https://user-images.githubusercontent.com/1761469/188454527-a2609467-b10c-4336-abeb-cd0d95949bd7.png)

Just tried on the github API, and… it's working, can you provide the openapi specs? 🤔

**Comment by fabien0102** [comment]
This is very strange, I can't see how you can have `ListLocationsResponse` defined in one place but not the other…

This is the same variable here in the generation
![image](https://user-images.githubusercontent.com/1761469/188455387-1c84accf-b73c-466c-88b3-51e1e6346fee.png)

I may have a last idea to explore, what's your version of typescript?

**Comment by Kordonme** [comment]
I had to strip the specification before sending. We use Typescript 4.7.4.

```yaml
openapi: 3.0.1
info:
  title: API
  description: API
  version: v1
  license:
    name: MIT
servers:
  - url: /api/v1
    description: Api version 1.0
paths:
  /locations:
    parameters:
      - name: customerId
        in: header
        required: false
        schema:
          type: string
          format: uuid
    get:
      summary: Retrieve all locations
      description: Retrieve all locations
      operationId: listLocations
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Location"
components:
  schemas:
    Location:
      title: Location
      type: object
      properties:
        id:
          type: string
          format: uuid
  requestBodies: {}
  responses: {}
```

**Comment by fabien0102** [comment]
Oki… `npm i typescript@latest` fixed it… (bumping to `4.8.2`)

So this is probably a fail during the dependency resolution or something like this. This is very strange, the package should work with `4.5.2` 😕 

Anyway, now that I can repro, I can try to fix it 😅

**Comment by needim** [comment]
Hi @Kordonme can you also share `npm ls typescript` output?

**Comment by fabien0102** [comment]
This definitely seams related! Amazing debugging 👌

**Comment by needim** [comment]
How did you repro btw? I can't.

**Comment by needim** [comment]
Hi again,

Created a sandbox to test with the versions provided and it still generated correct schemas and components. Maybe I am missing something?

[![Edit openapi-codegen-template-issue-88](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/openapi-codegen-template-issue-88-3vn5t8?expanddevtools=1&fontsize=14&module=%2Fissue88%2Fissue88Components.ts&theme=dark&view=editor)


-----

_A little of the topic idea but looks like it is related to this issue somehow._

_Maybe we can bump the typescript version to the latest for workspace packages or lock it to `4.5.2` for example. Typescript is not a `peerDependency` and this package always should be `devDependency`. So it shouldn't be a problem._

_`^4.5.2 -> 4.5.2` or `^4.5.2 -> 4.8.2` and can use controlled version bump_

_For the users, I think the important thing is if the generated code is working on their own TypeScript version. Not the version we use while generating code._

**Comment by fabien0102** [comment]
@needim the repro -> https://github.com/fabien0102/openapi-codegen-repro-88 (with npm as package manager)

And for the typescript version, since we are using typescript as a library as AST creator, we need to fix the version and be a dependency (and this is probably why this is failing for now, I forgot tha typescript is not following semver)

Nevertheless, I will be totally happy to update TS version, they often have new interesting stuff 😄

**Comment by fabien0102** [comment]
BTW, I bet this is an `npm` only issue, this is why this is working in your codesandbox

**Comment by needim** [comment]
yep, it failed with `npm` 🤦

**Comment by fabien0102** [comment]
Yep, let's bump and fix the version of typescript (no more `^` since `typescript` is not following semver), can you open the PR (please 👍 if yes)?

**Comment by fabien0102** [comment]
Works on the repro project with the version `5.2.0` 🎉 
![image](https://user-images.githubusercontent.com/1761469/188817908-cdf3eac2-219f-41d3-849d-8cf0c68f7d22.png)

Thanks @Kordonme & @needim for catching/debugging/fixing this nasty bug 😁
