### ISSUE TITLE
Enhancement: add eslint and tslint ignore/disable to generated files

### ISSUE THREAD

**Issue by bcucumber** [fabien0102/openapi-codegen#96]
Hi all,

First of all, great library!
I would like to suggest a simple enhancement over the current codebase that would help in the different dev environments, which would be adding tags to disable eslint and tslint in auto-generated files (since these might trigger formatting errors).

If I'm not wrong, the following at the top of each of the files should suffice:
`/* eslint-disable */`
`/* tslint:disable */`

I'm not completely sure if it's possible to customize it and add it current as it is, but I think this would be pretty useful.

You can check about this functionality from another library that autogenerates the client as well, for reference: https://github.com/acacode/swagger-typescript-api/blob/a6f16d7097db6df2c3d657eff3cc6786cef52331/tests/spec/readonly/schema.ts

Cheers

**Comment by fabien0102** [comment]
Hi!

You have currently two options:
- Add a `.eslintignore` -> https://eslint.org/docs/latest/user-guide/configuring/ignoring-code
- Customize the `writeFile` function in `openapi-codegen.config.ts`:

```diff
diff --git a/openapi-codegen.config.ts b/openapi-codegen.config.ts
index acc453a..9f7bb24 100644
--- a/openapi-codegen.config.ts
+++ b/openapi-codegen.config.ts
@@ -11,6 +11,10 @@ export default defineConfig({
     },
     outputDir: "src/repro",
     to: async (context) => {
+      const writeFile = context.writeFile;
+      context.writeFile = (file, data) =>
+        writeFile(file, `/* eslint-disable */\n\n${data}`);
+
       const filenamePrefix = "repro";
       const { schemasFiles } = await generateSchemaTypes(context, {
         filenamePrefix,
```

**Comment by needim** [comment]
In addition to @fabien0102's answer;

Hi @bcucumber!, I think also generated files also be added to `.gitignore` file. (they should be generated automatically via CI job or on dev env via start development scripts)

In my opinion, normally users have to manage generated files

**Comment by fabien0102** [comment]
For the record, I do prefer version control for those generated files, so every time you do `yarn gen` you have an amazing diff to review and you can see what are the new features available from your backend 😁

So no strong rules about this ^^

**Comment by needim** [comment]
Good point! 👍

**Comment by needim** [comment]
@bcucumber can we close this issue if you all agree?

**Comment by fabien0102** [comment]
I'm closing the issue for now, please ping me if this is not working for you and I can reopen the issue 😉

**Comment by bcucumber2** [comment]
> Hi!
> 
> You have currently two options:
> 
> * Add a `.eslintignore` -> https://eslint.org/docs/latest/user-guide/configuring/ignoring-code
> * Customize the `writeFile` function in `openapi-codegen.config.ts`:
> 
> ```diff
> diff --git a/openapi-codegen.config.ts b/openapi-codegen.config.ts
> index acc453a..9f7bb24 100644
> --- a/openapi-codegen.config.ts
> +++ b/openapi-codegen.config.ts
> @@ -11,6 +11,10 @@ export default defineConfig({
>      },
>      outputDir: "src/repro",
>      to: async (context) => {
> +      const writeFile = context.writeFile;
> +      context.writeFile = (file, data) =>
> +        writeFile(file, `/* eslint-disable */\n\n${data}`);
> +
>        const filenamePrefix = "repro";
>        const { schemasFiles } = await generateSchemaTypes(context, {
>          filenamePrefix,
> ```

Sorry for the delay, had a problem with my previous account as well. I would like you to know that the solution you presented here is perfect for the use case.

Thank you!
